apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-pvc
spec:
#     * 这个是随便写的, 只要pv里面有对应的就行
  storageClassName: record
#     * 控制能不能被多个pod读写
  accessModes:
#     * 被一个pod读写, 但不代表不会并发写, 因为一个 pod里可以有多个线程
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi