// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire_demo/cmd/wire_demo
//go:build !wireinject
// +build !wireinject

package wire_demo

import (
	"github.com/sgy111222333/basic-go/wire_demo/repository"
	"github.com/sgy111222333/basic-go/wire_demo/repository/dao"
)

// Injectors from wire_demo.go:

func InitUserRepository() *repository.UserRepository {
	db := InitDB()
	userDAO := dao.NewUserDAO(db)
	userRepository := repository.NewUserRepository(userDAO)
	return userRepository
}
